### ISSUE TITLE
@parcel/watcher prebuild not found in nrwl.angular-console

### ISSUE THREAD

**Issue by sarahec** [nix-community/nix-vscode-extensions#40]
I'm attempting to get the [nx console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console) to work. The console opens, but then throws up error about its client not working. The console is inoperable after that.

```
Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-x64-glibc. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (/nix/store/hpxn0nksskra5x476x1dab5abpi5l706-vscode-extension-nrwl-angular-console-18.6.0/share/vscode/extensions/nrwl.angular-console/node_modules/@parcel/watcher/index.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/nix/store/hpxn0nksskra5x476x1dab5abpi5l706-vscode-extension-nrwl-angular-console-18.6.0/share/vscode/extensions/nrwl.angular-console/nxls/main.js:776:22675)
    at Module._compile (node:internal/modules/cjs/loader:1188:14)
[Error - 11:25:43 AM] The Nx Console Client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 11:25:43 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:25:43 AM] Nx Console Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:25:43 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

Installing a local or global copy of @parcel/watcher doesn't help. See also https://github.com/nrwl/nx-console/issues/1808

**Comment by deemp** [comment]
@sarahec, please, provide a flake with a reproduction.

**Comment by sarahec** [comment]
I found the build result and confirmed that all the pieces are there, so this build is running correctly. I'm going to close this bug and follow up on the nx side.

**Comment by sarahec** [comment]
Closed, not a nix build problem.
